name: Manual Release Workflow

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main and pull upstream master
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Git Pull main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Create and checkout new branch
        run: git checkout -b bump-$(date +"%m-%d-%Y")-branch


      - name: Install jq
        run: sudo apt-get install jq

      - name: Bump Version in package.json
        id: bump_version_step
        run: |
          current_version=$(jq -r '.version' taco-shop/package.json)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          jq --arg new_version "$new_version" '.version |= $new_version' taco-shop/package.json package.json > temp.json && mv temp.json taco-shop/package.json
          echo "::set-output name=version::$new_version"

      - name: Update Changelog
        run: |
          # Perform actions to update the changelog with new version
          # Example: (Replace this with your logic)
          sed -i 's/\[Unreleased\]/[${{ steps.bump_version.outputs.version }}]/g' CHANGELOG.md

      - name: Commit Changes
        run: |
          git config --global user.email "senorTaquero@tacos.com"
          git config --global user.name "Don Taquero"
          git add taco-shop/package.json CHANGELOG.md
          git commit -m "Bump version to ${{ steps.bump_version.outputs.version }}"
    

      - name: Create tag
        run: |
          git tag -a "v-${version}" -m "Version ${version}"

      # Add or update this step in your workflow YAML file

      - name: Push branch
        run: |
          git remote add origin_with_token "https://github.com/${{ github.repository }}"
          git push --set-upstream origin_with_token bump-$(date +"%m-%d-%Y")-branch
        env:  
          TOKEN: ${{ secrets.OAUTH_POC }}




