name: Manual Release Workflow

on:
  workflow_dispatch: # This event allows manual triggering

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main and pull upstream master
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Git Pull main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Create and checkout new branch
        run: |
          branch_name="bump-$(date +'%m-%d-%Y-%H-%M-%S')-branch"
          git checkout -b "$branch_name"
          git push --set-upstream origin "$branch_name"


      - name: Bump package.json version and save the value
        run: |
          version=$(node -p "require('./package.json').version")
          echo "Version: $version"

      - name: Update Changelog
        run: |
          # Perform actions to update the changelog with new version
          # Example: (Replace this with your logic)
          sed -i 's/\[Unreleased\]/[${{ steps.bump_version_step.outputs.version }}]/g' CHANGELOG.md

      - name: Commit Changes
        run: |
          git config --global user.email "senorTaquero@tacos.com"
          git config --global user.name "Don Taquero"
          git add taco-shop/package.json CHANGELOG.md
          git commit -m "Bump version to ${{ steps.bump_version.outputs.version }}"
    

      - name: Create tag
        run: |
          git tag -a "v-${version}" -m "Version ${version}"

      # Add or update this step in your workflow YAML file

      - name: Push branch
        run: git push origin "v-${version}"




