name: MS Teams Notification

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        id: notify
        uses: thechetantalwar/teams-notify@v2        
        with:
          teams_webhook_url: ${{ secrets.MS_TEAM }}
          message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is  ${{ needs.build.result }}."

